# LevitateChat configuration file : version 1.0

# Change the chat format through here!
chat_format: '%username: %message'

# Change the automatic messages shown in-game and their delay through here!
automessages_enabled: true
Message1: '&aThis is an automatic message, the text can be changed in the LevitateChat config file!'
Message2: '&aThis is an automatic message, the text can be changed in the LevitateChat config file!'
Message3: '&aThis is an automatic message, the text can be changed in the LevitateChat config file!'
Message4: '&aThis is an automatic message, the text can be changed in the LevitateChat config file!'
Message5: '&aThis is an automatic message, the text can be changed in the LevitateChat config file!'
MessageDelay: 120

# Change the staff-chat message format through here!
staffchat_enabled: true
staffchat_format: '&c&lSTAFFCHAT&f %username: %message'

# Change the anti-swear settings here!
antiswear_enabled: true
blockedwords:
  - 'anal'
  - 'anus'
  - 'arse'
  - 'ass'
  - 'ballsack'
  - 'balls'
  - 'bastard'
  - 'bitch'
  - 'biatch'
  - 'bloody'
  - 'blowjob'
  - 'blow job'
  - 'bollock'
  - 'bollok'
  - 'boner'
  - 'boob'
  - 'bugger'
  - 'bum'
  - 'butt'
  - 'buttplug'
  - 'clitoris'
  - 'cock'
  - 'coon'
  - 'crap'
  - 'cunt'
  - 'damn'
  - 'dick'
  - 'dildo'
  - 'dyke'
  - 'fag'
  - 'feck'
  - 'fellate'
  - 'fellatio'
  - 'felching'
  - 'fuck'
  - 'f u c k'
  - 'fudgepacker'
  - 'fudge packer'
  - 'flange'
  - 'Goddamn'
  - 'God damn'
  - 'hell'
  - 'homo'
  - 'jerk'
  - 'jizz'
  - 'knobend'
  - 'knob end'
  - 'labia'
  - 'muff'
  - 'nigger'
  - 'nigga'
  - 'omg'
  - 'penis'
  - 'piss'
  - 'poop'
  - 'prick'
  - 'pube'
  - 'pussy'
  - 'queer'
  - 'scrotum'
  - 'sex'
  - 'shit'
  - 's hit'
  - 'sh1t'
  - 'slut'
  - 'smegma'
  - 'spunk'
  - 'tit'
  - 'tosser'
  - 'turd'
  - 'twat'
  - 'vagina'
  - 'wank'
  - 'whore'

# Change the anti-spam settings through here!
antispam_enabled: true
antispam_timer: 3